###############################################
######### Joint Trajectory Controller  ########
###############################################
VelocityControllers_JointTrajectoryController:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6

  gains: # Required because we're controlling a velocity interface
    J1: {p: 20,  d: 0, i: 1, i_clamp: 0}
    J2: {p: 20,  d: 0, i: 1, i_clamp: 0}
    J3: {p: 20,  d: 0, i: 1, i_clamp: 0}
    J4: {p: 20,  d: 0, i: 1, i_clamp: 0}
    J5: {p: 20,  d: 0, i: 1, i_clamp: 0}
    J6: {p: 20,  d: 0, i: 1, i_clamp: 0}

robot:
  pos_corr_gain: 0 # parameter in RAPID that needs to be set to zero to accept velocity commands alone